
version: '3.11'
 
services:
  api-1:
    build:
      context: ./api
    ports:
      - "80:80"
    volumes:
      - ./api:/app
 
  frontend-1:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - api-1

